# Generated by Django 4.0.4 on 2022-05-07 13:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'pbx_menus',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('link', models.CharField(blank=True, max_length=128, null=True, verbose_name='Link')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='Icon')),
                ('category', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('e-mail', 'E-Mail')], default='internal', max_length=16, verbose_name='Target')),
                ('protected', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=8, verbose_name='Protected')),
                ('sequence', models.DecimalField(decimal_places=0, default=10, max_digits=11, verbose_name='Order')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('menu_id', models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, to='portal.menu', verbose_name='Menu')),
                ('parent_id', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.menuitem', verbose_name='Parent Menu Item')),
            ],
            options={
                'db_table': 'pbx_menu_items',
            },
        ),
        migrations.CreateModel(
            name='MenuItemGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group')),
                ('menu_item_id', models.ForeignKey(db_column='menu_item_id', on_delete=django.db.models.deletion.CASCADE, to='portal.menuitem', verbose_name='Menu Item')),
            ],
            options={
                'db_table': 'pbx_menu_item_groups',
            },
        ),
    ]
