# Generated by Django 4.0.4 on 2023-11-05 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failed_logins',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('username', models.CharField(blank=True, max_length=254, null=True, verbose_name='User ID')),
                ('attempts', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Attempts')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(default='system', max_length=64, verbose_name='Updated by')),
            ],
            options={
                'verbose_name_plural': 'Failed Logins',
                'db_table': 'pbx_failed_logins',
            },
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='protected',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Protected'),
        ),
    ]
