# Generated by Django 4.0.4 on 2023-11-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_failed_logins_alter_menuitem_protected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failed_logins',
            name='attempts',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4, verbose_name='Attempts'),
        ),
    ]
