# Generated by Django 4.0.4 on 2023-06-06 19:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_alter_defaultsetting_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Contact ID')),
                ('fn', models.CharField(help_text='The formatted name string associated with the vCard', max_length=254, verbose_name='Display Name')),
                ('family_name', models.CharField(max_length=64, verbose_name='Last Name')),
                ('given_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='First Name')),
                ('additional_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Middle Name')),
                ('honorific_prefix', models.CharField(blank=True, max_length=32, null=True, verbose_name='Prefix')),
                ('honorific_suffix', models.CharField(blank=True, max_length=32, null=True, verbose_name='Suffix')),
                ('nickname', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nickname')),
                ('timezone', models.CharField(blank=True, max_length=128, null=True, verbose_name='Timezone')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('enabled', models.CharField(blank=True, choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('domain_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.domain', verbose_name='Domain')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.profile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'pbx_contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Geo Tag ID')),
                ('url', models.CharField(max_length=1024, verbose_name='URL (Website)')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': "URL's",
                'db_table': 'pbx_contacts_url',
            },
        ),
        migrations.CreateModel(
            name='ContactTel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Telephone ID')),
                ('tel_type', models.CharField(choices=[('VOICE', 'INTL'), ('HOME', 'Home'), ('MSG', 'Message'), ('WORK', 'Work'), ('pref', 'Preferred'), ('fax', 'Fax'), ('cell', 'Mobile phone'), ('video', 'Video'), ('pager', 'Pager'), ('bbs', 'BBS'), ('modem', 'Modem'), ('car', 'Car phone'), ('isdn', 'ISDN'), ('pcs', 'PCS')], default='WORK', help_text='for example WORK or HOME', max_length=32, verbose_name='Type of Phone Number')),
                ('number', models.CharField(max_length=128, verbose_name='Number')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Telephone',
                'verbose_name_plural': 'Telephones',
                'db_table': 'pbx_contacts_tel',
            },
        ),
        migrations.CreateModel(
            name='ContactOrg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Organisation')),
                ('organisation_name', models.CharField(max_length=128, verbose_name='Organisation Name')),
                ('organisation_unit', models.CharField(blank=True, max_length=128, verbose_name='Organisation Unit')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'pbx_contacts_org',
            },
        ),
        migrations.CreateModel(
            name='ContactGeo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Geo Tag ID')),
                ('geo_uri', models.CharField(max_length=1024, verbose_name='Geographic URI')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Geoghraphic URI',
                'verbose_name_plural': "Geoghraphic URI's",
                'db_table': 'pbx_contacts_geo',
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Email ID')),
                ('email_type', models.CharField(choices=[('INTERNET', 'Internet'), ('x400', 'x400'), ('pref', 'Preferred')], default='INTERNET', max_length=16, verbose_name='Type of Email')),
                ('email', models.CharField(max_length=1024, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'db_table': 'pbx_contacts_email',
            },
        ),
        migrations.CreateModel(
            name='ContactDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Significant Date')),
                ('sig_date', models.DateField(blank=True, null=True, verbose_name='Significant Date')),
                ('label', models.CharField(max_length=64, verbose_name='Label')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Significant Date',
                'verbose_name_plural': 'Significant Dates',
                'db_table': 'pbx_contacts_dates',
            },
        ),
        migrations.CreateModel(
            name='ContactCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Significant Date')),
                ('category', models.CharField(max_length=64, verbose_name='Label')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'pbx_contacts_category',
            },
        ),
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Email ID')),
                ('post_office_box', models.CharField(blank=True, max_length=64, verbose_name='Post Office Box')),
                ('extended_address', models.CharField(blank=True, max_length=128, verbose_name='Extended Address')),
                ('street_address', models.CharField(max_length=128, verbose_name='Street Address')),
                ('locality', models.CharField(max_length=128, verbose_name='Locality')),
                ('region', models.CharField(max_length=128, verbose_name='Region')),
                ('postal_code', models.CharField(max_length=16, verbose_name='Postal Code')),
                ('country_name', models.CharField(max_length=128, verbose_name='Country Name')),
                ('addr_type', models.CharField(choices=[('INTL', 'INTL'), ('POSTAL', 'Postal'), ('PARCEL', 'Parcel'), ('WORK', 'Work'), ('dom', 'Dom'), ('home', 'Home'), ('pref', 'Preferred')], default='WORK', max_length=16, verbose_name='Type')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'pbx_contacts_address',
            },
        ),
    ]
