# Generated by Django 4.0.4 on 2023-12-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_url_contacturl_url_uri_contactgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttel',
            name='speed_dial',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Speed Dial'),
        ),
    ]
