# Generated by Django 4.0.4 on 2023-12-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contacttel_speed_dial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactaddress',
            name='addr_type',
            field=models.CharField(choices=[('intl', 'INTL'), ('postal', 'Postal'), ('parcel', 'Parcel'), ('work', 'Work'), ('dom', 'Dom'), ('home', 'Home'), ('pref', 'Preferred')], default='work', max_length=16, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='contactemail',
            name='email_type',
            field=models.CharField(choices=[('internet', 'Internet'), ('home', 'Home'), ('work', 'Work'), ('x400', 'x400'), ('pref', 'Preferred')], default='internet', max_length=16, verbose_name='Type of Email'),
        ),
        migrations.AlterField(
            model_name='contacttel',
            name='tel_type',
            field=models.CharField(choices=[('voice', 'INTL'), ('home', 'Home'), ('msg', 'Message'), ('work', 'Work'), ('pref', 'Preferred'), ('fax', 'Fax'), ('cell', 'Mobile phone'), ('video', 'Video'), ('pager', 'Pager'), ('bbs', 'BBS'), ('modem', 'Modem'), ('car', 'Car phone'), ('isdn', 'ISDN'), ('pcs', 'PCS')], default='work', help_text='for example WORK or HOME', max_length=32, verbose_name='Type of Phone Number'),
        ),
    ]
