# Generated by Django 5.0.1 on 2024-08-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contactaddress_addr_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactaddress',
            name='country_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='contactaddress',
            name='extended_address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Extended Address'),
        ),
        migrations.AlterField(
            model_name='contactaddress',
            name='locality',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='contactaddress',
            name='post_office_box',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Post Office Box'),
        ),
        migrations.AlterField(
            model_name='contactaddress',
            name='region',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Region'),
        ),
    ]
