# Generated by Django 4.0.4 on 2023-10-30 13:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_alter_defaultsetting_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Phrase')),
                ('name', models.CharField(blank=True, help_text='Enter a name (Example: abc_audio)', max_length=64, null=True, verbose_name='Name')),
                ('language', models.CharField(default='en', help_text='Language used in the phrase', max_length=8, verbose_name='Language')),
                ('enabled', models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', help_text='Set the status of the phrase', max_length=8, verbose_name='Enabled')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('domain_id', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name_plural': 'Phrases',
                'db_table': 'pbx_phrases',
            },
        ),
        migrations.CreateModel(
            name='PhraseDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Phrase Detail')),
                ('pfunction', models.CharField(choices=[('play-file', 'Play'), ('execute', 'Execute')], default='play-file', max_length=16, verbose_name='Function')),
                ('data', models.CharField(blank=True, max_length=254, null=True, verbose_name='Action')),
                ('sequence', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('phrase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phrases.phrases', verbose_name='Phrase')),
            ],
            options={
                'verbose_name_plural': 'Phrase Details',
                'db_table': 'pbx_phrase_details',
            },
        ),
    ]
