# Generated by Django 4.0.4 on 2023-04-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provision', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicekeys',
            options={'verbose_name_plural': 'Device Keys'},
        ),
        migrations.AlterModelOptions(
            name='devicelines',
            options={'verbose_name_plural': 'Device Lines'},
        ),
        migrations.AlterModelOptions(
            name='deviceprofilekeys',
            options={'verbose_name_plural': 'Device Profile Keys'},
        ),
        migrations.AlterModelOptions(
            name='deviceprofiles',
            options={'verbose_name_plural': 'Device Profiles'},
        ),
        migrations.AlterModelOptions(
            name='deviceprofilesettings',
            options={'verbose_name_plural': 'Device Profile Settings'},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='devicesettings',
            options={'verbose_name_plural': 'Device Settings'},
        ),
        migrations.AlterModelOptions(
            name='devicevendorfunctiongroups',
            options={'verbose_name_plural': 'Device Vendor Function Groups'},
        ),
        migrations.AlterModelOptions(
            name='devicevendorfunctions',
            options={'verbose_name_plural': 'Device Vendor Functions'},
        ),
        migrations.AlterModelOptions(
            name='devicevendors',
            options={'verbose_name_plural': 'Device Vendors'},
        ),
        migrations.AlterField(
            model_name='devicelines',
            name='sip_transport',
            field=models.CharField(blank=True, choices=[('udp', 'UDP'), ('tcp', 'TCP'), ('tls', 'TLS'), ('dns srv', 'DNS SRV')], default='udp', max_length=254, null=True, verbose_name='Transport'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='provisioned_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='Provisioned Address'),
        ),
    ]
