# Generated by Django 5.0.1 on 2024-05-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provision', '0006_alter_devicekeys_key_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='alternate_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Alternate Device'),
        ),
    ]
