# Generated by Django 4.0.4 on 2023-01-04 19:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceControls',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Conference Controls')),
                ('name', models.CharField(default='new', max_length=32, verbose_name='Name')),
                ('enabled', models.CharField(blank=True, choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
            ],
            options={
                'verbose_name_plural': 'Conference Controls',
                'db_table': 'pbx_conference_controls',
            },
        ),
        migrations.CreateModel(
            name='ConferenceProfiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Conference Profiles')),
                ('name', models.CharField(default='default', max_length=32, verbose_name='Name')),
                ('enabled', models.CharField(blank=True, choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled')),
                ('description', models.CharField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
            ],
            options={
                'verbose_name_plural': 'Conference Profiles',
                'db_table': 'pbx_conference_profiles',
            },
        ),
        migrations.CreateModel(
            name='ConferenceProfileParams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Conference Profile Params')),
                ('name', models.CharField(default='new', max_length=64, verbose_name='Name')),
                ('value', models.CharField(blank=True, max_length=254, null=True, verbose_name='Value')),
                ('enabled', models.CharField(blank=True, choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled')),
                ('description', models.CharField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('conf_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferencesettings.conferenceprofiles', verbose_name='Conference Profile')),
            ],
            options={
                'verbose_name_plural': 'Conference Profile Params',
                'db_table': 'pbx_conference_profile_params',
            },
        ),
        migrations.CreateModel(
            name='ConferenceControlDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Conference Control Details')),
                ('digits', models.CharField(default='0', max_length=8, verbose_name='Digits')),
                ('action', models.CharField(default='mute', max_length=64, verbose_name='Action')),
                ('data', models.CharField(blank=True, max_length=254, null=True, verbose_name='Data')),
                ('enabled', models.CharField(blank=True, choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('conf_ctrl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferencesettings.conferencecontrols', verbose_name='Conference Control')),
            ],
            options={
                'verbose_name_plural': 'Conference Control Details',
                'db_table': 'pbx_conference_control_details',
            },
        ),
    ]
