# Generated by Django 4.0.4 on 2023-11-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencesettings', '0002_conferencecentres_conferencerooms_conferenceroomuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencerooms',
            name='moderator_pin',
            field=models.CharField(default='26994', max_length=16, verbose_name='Moderator PIN'),
        ),
        migrations.AlterField(
            model_name='conferencerooms',
            name='mute',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=8, verbose_name='Mute'),
        ),
        migrations.AlterField(
            model_name='conferencerooms',
            name='participant_pin',
            field=models.CharField(default='85121', max_length=16, verbose_name='Participant PIN'),
        ),
        migrations.AlterField(
            model_name='conferencerooms',
            name='record',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=8, verbose_name='Record'),
        ),
        migrations.AlterField(
            model_name='conferencerooms',
            name='sounds',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=8, verbose_name='Sounds'),
        ),
    ]
