# Generated by Django 4.0.4 on 2023-11-17 22:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conferencesettings', '0004_alter_conferencerooms_moderator_pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSessions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Conference Session')),
                ('caller_id_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Caller Id Name')),
                ('caller_id_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Caller Id Number')),
                ('profile', models.CharField(blank=True, max_length=32, null=True, verbose_name='Profile')),
                ('live', models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled')),
                ('recording', models.CharField(blank=True, max_length=256, null=True, verbose_name='Recording')),
                ('start', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Start')),
                ('end', models.DateTimeField(auto_now=True, null=True, verbose_name='End')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('c_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferencesettings.conferencerooms', verbose_name='Conference Room')),
            ],
            options={
                'verbose_name_plural': 'Conference Sessions',
                'db_table': 'pbx_conference_sessions',
            },
        ),
    ]
