# Generated by Django 4.0.4 on 2023-11-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencesettings', '0005_conferencesessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesessions',
            name='live',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Live'),
        ),
    ]
