# Generated by Django 5.0.1 on 2024-07-29 15:18

import pbx.commonwidgets
import recordings.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_alter_recording_options_callrecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecording',
            name='filename',
            field=pbx.commonwidgets.PbxFileField(storage=recordings.models.select_storage, upload_to=recordings.models.call_recording_directory_path, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='filename',
            field=pbx.commonwidgets.PbxFileField(storage=recordings.models.select_storage, upload_to=recordings.models.user_directory_path, verbose_name='File Name'),
        ),
    ]
