# Generated by Django 5.0.1 on 2024-08-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_alter_callrecording_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='filestore',
            field=models.CharField(default='localhost', max_length=128, verbose_name='Filestore'),
        ),
        migrations.AddField(
            model_name='recording',
            name='filestore',
            field=models.CharField(default='localhost', max_length=128, verbose_name='Filestore'),
        ),
    ]
