# Generated by Django 5.0.1 on 2024-08-10 14:04

import recordings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_callrecording_filestore_recording_filestore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecording',
            name='filestore',
            field=models.CharField(default=recordings.models.default_filestore, max_length=128, verbose_name='Filestore'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='filestore',
            field=models.CharField(default=recordings.models.default_filestore, max_length=128, verbose_name='Filestore'),
        ),
    ]
