# Generated by Django 4.0.4 on 2024-01-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringgroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringgroup',
            name='strategy',
            field=models.CharField(blank=True, choices=[('simultaneous', 'Simultaneous'), ('sequence', 'Sequence'), ('enterprise', 'Enterprise'), ('rollover', 'Rollover'), ('random', 'Random')], default='simultaneous', help_text='Select the ring strategy', max_length=16, null=True, verbose_name='Strategy'),
        ),
        migrations.AlterField(
            model_name='ringgroup',
            name='timeout_data',
            field=models.CharField(blank=True, help_text='Select the timeout destination  for this ring group', max_length=256, null=True, verbose_name='Timeout Destination'),
        ),
    ]
