# Generated by Django 5.0.1 on 2024-02-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringgroups', '0002_alter_ringgroup_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringgroupdestination',
            name='destination_prompt',
            field=models.DecimalField(choices=[(0, ''), (1, 'Confirm')], decimal_places=0, default=0, max_digits=3, verbose_name='Prompt'),
        ),
    ]
