# Generated by Django 4.0.4 on 2023-11-20 11:03

import callcentres.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_alter_defaultsetting_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCentreAgents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Call Centre Agent')),
                ('name', models.CharField(blank=True, help_text='Enter a name', max_length=64, null=True, verbose_name='Name')),
                ('agent_type', models.CharField(blank=True, choices=[('callback', 'Call Back'), ('uuid-standby', 'UUID Standby')], default='callback', max_length=16, null=True, verbose_name='Type')),
                ('call_timeout', models.DecimalField(decimal_places=0, default=20, max_digits=3, verbose_name='Call Timeout')),
                ('agent_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Agent Id')),
                ('agent_pin', models.CharField(default=callcentres.models.random_pin, max_length=16, verbose_name='Agent PIN')),
                ('contact', models.CharField(blank=True, help_text='Select the contact destination (eg. extension)', max_length=256, null=True, verbose_name='Contact')),
                ('status', models.CharField(blank=True, choices=[('', ''), ('Logged Out', 'Logged Out'), ('Available', 'Available'), ('Available (On Demand)', 'Available (On Demand)'), ('On Break', 'On Break')], default='', help_text='Sets the default status', max_length=32, null=True, verbose_name='Status')),
                ('data', models.CharField(default='false', max_length=64, verbose_name='Agent Data')),
                ('no_answer_delay_time', models.DecimalField(decimal_places=0, default=30, max_digits=3, verbose_name='No Answer Delay Time')),
                ('max_no_answer', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Max No Answer')),
                ('wrap_up_time', models.DecimalField(decimal_places=0, default=10, max_digits=3, verbose_name='Wrap Up Time')),
                ('reject_delay_time', models.DecimalField(decimal_places=0, default=90, max_digits=3, verbose_name='Reject Delay Time')),
                ('busy_delay_time', models.DecimalField(decimal_places=0, default=90, max_digits=3, verbose_name='Busy Delay Time')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('domain_id', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.domain', verbose_name='Domain')),
                ('user_uuid', models.ForeignKey(blank=True, db_column='user_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.profile', to_field='user_uuid', verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Call Centre Agents',
                'db_table': 'pbx_call_centre_agents',
            },
        ),
        migrations.CreateModel(
            name='CallCentreQueues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Call Centre Agent')),
                ('name', models.CharField(blank=True, help_text='Enter a name', max_length=64, null=True, verbose_name='Name')),
                ('extension', models.CharField(help_text='Enter the extension number for this Call Centre', max_length=32, verbose_name='Extension')),
                ('greeting', models.CharField(blank=True, help_text='Select the desired Greeting or leave blank', max_length=256, null=True, verbose_name='Greeting')),
                ('strategy', models.CharField(blank=True, choices=[('ring-all', 'Ring All'), ('longest-idle-agent', 'Longest Idle Agent'), ('round-robin', 'Round Robin'), ('top-down', 'Top Down'), ('agent-with-least-talk-time', 'Agent With Least Talk Time'), ('agent-with-fewest-calls', 'Agent With Fewest Calls'), ('sequentially-by-agent-order', 'Sequentially By Agent Order'), ('sequentially-by-next-agent-order', 'Sequentially By Next Agent Order'), ('random', 'Random')], default='longest-idle-agent', max_length=32, null=True, verbose_name='Strategy')),
                ('moh_sound', models.CharField(blank=True, help_text='Select the desired hold music', max_length=256, null=True, verbose_name='Musin On Hold')),
                ('record_template', models.CharField(blank=True, help_text='Save a recording', max_length=256, null=True, verbose_name='Record')),
                ('time_base_score', models.CharField(blank=True, choices=[('system', 'System'), ('queue', 'Queue')], default='system', max_length=16, null=True, verbose_name='Time Base Score')),
                ('max_wait_time', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Max Wail Time')),
                ('max_wait_time_na', models.DecimalField(decimal_places=0, default=90, max_digits=3, verbose_name='Max Wait Time with No Agent')),
                ('max_wait_time_natr', models.DecimalField(decimal_places=0, default=30, max_digits=3, verbose_name='Max Wait Time with No Agent Time Reached')),
                ('timeout_action', models.CharField(blank=True, help_text='Select the destination when the max wait time is reached.', max_length=256, null=True, verbose_name='Timeout Destination')),
                ('tier_rules_apply', models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Tier Rules Apply')),
                ('tier_rule_wait_sec', models.DecimalField(decimal_places=0, default=30, max_digits=3, verbose_name='Tier Rule Wait Second')),
                ('tier_rule_wm_level', models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Tier Rule Wait Multiply Level')),
                ('tier_rule_nanw', models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Tier Rule No Agent No Wait')),
                ('discard_abndnd_after', models.DecimalField(decimal_places=0, default=900, max_digits=4, verbose_name='Discard Abandoned After')),
                ('abndnd_resume_allowed', models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Abandoned Resume Allowed')),
                ('cid_name_prefix', models.CharField(blank=True, help_text='Set a prefix on the caller ID name', max_length=32, null=True, verbose_name='CID Name Prefix')),
                ('announce_sound', models.CharField(blank=True, help_text='sound to play to a caller every announce sound seconds. Needs the full path to the wav file', max_length=256, null=True, verbose_name='Announce Sound')),
                ('announce_frequency', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=3, null=True, verbose_name='Announce Frequency')),
                ('cc_exit_keys', models.CharField(blank=True, help_text='Keys to quit the current queue waiting', max_length=8, null=True, verbose_name='Exit Key')),
                ('enabled', models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='Description')),
                ('dialplan_id', models.UUIDField(blank=True, null=True, verbose_name='Dialplan UUID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('domain_id', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name_plural': 'Call Centre Queues',
                'db_table': 'pbx_call_centre_queues',
            },
        ),
        migrations.CreateModel(
            name='CallCentreTiers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Call Centre Tier')),
                ('tier_level', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Tier Level')),
                ('tier_position', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Tier Position')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callcentres.callcentreagents', verbose_name='Call Centre Agent')),
                ('queue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callcentres.callcentrequeues', verbose_name='Call Centre Queue')),
            ],
            options={
                'verbose_name_plural': 'Call Centre Tiers',
                'db_table': 'pbx_call_centre_tiers',
            },
        ),
    ]
