# Generated by Django 4.0.4 on 2023-11-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_defaultsetting_subcategory_and_more'),
        ('callcentres', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='callcentreagents',
            unique_together={('domain_id', 'agent_id')},
        ),
    ]
