# Generated by Django 4.0.4 on 2024-01-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcentres', '0003_callcentrequeues_wb_aban_crit_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcentrequeues',
            name='moh_sound',
            field=models.CharField(blank=True, help_text='Select the desired hold music', max_length=256, null=True, verbose_name='Music On Hold'),
        ),
    ]
