# Generated by Django 4.0.4 on 2022-11-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultsetting',
            name='category',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='defaultsetting',
            name='subcategory',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='defaultsetting',
            name='value_type',
            field=models.CharField(choices=[('text', 'text'), ('numeric', 'numeric'), ('array', 'array'), ('boolean', 'boolean'), ('code', 'code'), ('uuid', 'uuid'), ('name', 'name'), ('var', 'var'), ('dir', 'dir')], db_index=True, default='text', max_length=32, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='domainsetting',
            name='category',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='domainsetting',
            name='subcategory',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='domainsetting',
            name='value_type',
            field=models.CharField(choices=[('text', 'text'), ('numeric', 'numeric'), ('array', 'array'), ('boolean', 'boolean'), ('code', 'code'), ('uuid', 'uuid'), ('name', 'name'), ('var', 'var'), ('dir', 'dir')], db_index=True, default='text', max_length=32, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='profilesetting',
            name='category',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='profilesetting',
            name='subcategory',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='profilesetting',
            name='value_type',
            field=models.CharField(choices=[('text', 'text'), ('numeric', 'numeric'), ('array', 'array'), ('boolean', 'boolean'), ('code', 'code'), ('uuid', 'uuid'), ('name', 'name'), ('var', 'var'), ('dir', 'dir')], db_index=True, default='text', max_length=32, verbose_name='Type'),
        ),
    ]
