# Generated by Django 4.0.4 on 2022-12-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_defaultsetting_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultsetting',
            name='enabled',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='enabled',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='domainsetting',
            name='enabled',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='enabled',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='profilesetting',
            name='enabled',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled'),
        ),
    ]
