# Generated by Django 4.0.4 on 2023-05-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_defaultsetting_enabled_alter_domain_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultsetting',
            name='subcategory',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='domainsetting',
            name='subcategory',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='profilesetting',
            name='subcategory',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Subcategory'),
        ),
    ]
