# Generated by Django 5.0.1 on 2024-08-10 16:02

import django.db.models.deletion
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_failed_logins_attempts'),
        ('tenants', '0004_alter_defaultsetting_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='home_switch',
            field=models.CharField(default=tenants.models.default_switch, help_text='The Switch to which this domain is assigned', max_length=128, verbose_name='Home Switch'),
        ),
        migrations.AddField(
            model_name='domain',
            name='menu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.menu', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(db_index=True, help_text='Eg. tenant1.djangopbx.com', max_length=128, unique=True, verbose_name='Name'),
        ),
    ]
