# Generated by Django 5.0.1 on 2024-08-10 16:03

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_domain_home_switch_domain_menu_id_alter_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='portal_name',
            field=models.CharField(db_index=True, default=tenants.models.default_portal, help_text='Eg. tenant1.pbxportal.com', max_length=128, null=True, verbose_name='Portal Name'),
        ),
    ]
