# Generated by Django 5.0.1 on 2024-08-10 16:04

from django.db import migrations
import uuid


def gen_portal_name(apps, schema_editor):
    MyModel = apps.get_model("tenants", "Domain")
    for row in MyModel.objects.all():
        row.portal_name = '%s.com' % uuid.uuid4()
        row.save(update_fields=["portal_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_domain_portal_name'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_portal_name, reverse_code=migrations.RunPython.noop),
    ]
