# Generated by Django 4.0.4 on 2023-11-08 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberTranslations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Number Translation')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
                ('enabled', models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
            ],
            options={
                'verbose_name_plural': 'Number Translations',
                'db_table': 'pbx_number_translations',
            },
        ),
        migrations.CreateModel(
            name='NumberTranslationDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Number Translation Detail')),
                ('td_regex', models.CharField(blank=True, max_length=128, null=True, verbose_name='Regular Expression')),
                ('td_replace', models.CharField(blank=True, max_length=128, null=True, verbose_name='Replace')),
                ('td_order', models.DecimalField(decimal_places=0, default=10, max_digits=3, verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('number_translation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numbertranslations.numbertranslations', verbose_name='Number Translation')),
            ],
            options={
                'verbose_name_plural': 'Number Translation Details',
                'db_table': 'pbx_number_translation_details',
            },
        ),
    ]
