# Generated by Django 4.0.4 on 2023-01-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttApiSession',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Session_ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('xml', models.TextField(blank=True, null=True, verbose_name='XML')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='json')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
            options={
                'db_table': 'pbx_httapi_session',
            },
        ),
    ]
