# Generated by Django 4.0.4 on 2022-11-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_followmedestination_extension_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionuser',
            name='default_user',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=8, verbose_name='Default'),
        ),
    ]
