# Generated by Django 4.0.4 on 2022-11-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_extensionuser_default_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='extension',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='number_alias',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name='Number Alias'),
        ),
    ]
