# Generated by Django 4.0.4 on 2022-11-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_extension_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionuser',
            name='extension_id',
            field=models.ForeignKey(blank=True, db_column='extension_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extensionuser', to='accounts.extension', verbose_name='Extension'),
        ),
    ]
