# Generated by Django 4.0.4 on 2022-11-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_extensionuser_extension_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='missed_call_data',
            field=models.CharField(blank=True, help_text='Typically an email address or comma separated addresses', max_length=256, null=True, verbose_name='Missed Call Data'),
        ),
    ]
