# Generated by Django 4.0.4 on 2023-01-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_defaultsetting_enabled_alter_domain_enabled_and_more'),
        ('accounts', '0008_alter_extension_call_screen_enabled_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extension',
            unique_together={('domain_id', 'extension'), ('domain_id', 'number_alias')},
        ),
    ]
