# Generated by Django 5.0.1 on 2024-03-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_extension_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='auth_username',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Auth Username'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='codec_prefs',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Codec Preferences'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='extension',
            field=models.CharField(blank=True, default='auto_to_user', max_length=64, null=True, verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='from_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='From User'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gateway',
            field=models.CharField(max_length=64, verbose_name='Gateway'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='password',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Username'),
        ),
    ]
