# Generated by Django 4.0.4 on 2023-11-08 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_alter_defaultsetting_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IvrMenus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='IVR Menu')),
                ('dialplan_id', models.UUIDField(blank=True, null=True, verbose_name='Dialplan UUID')),
                ('name', models.CharField(blank=True, help_text='Enter a name', max_length=64, null=True, verbose_name='Name')),
                ('extension', models.CharField(help_text='Enter the extension number for this menu', max_length=32, verbose_name='Extension')),
                ('lanuage', models.CharField(blank=True, max_length=32, null=True, verbose_name='Language')),
                ('greet_long', models.CharField(blank=True, help_text='The long greeting is played when entering the menu', max_length=254, null=True, verbose_name='Greeting Long')),
                ('greet_short', models.CharField(blank=True, help_text='The short greeting is played when returning to the menu', max_length=254, null=True, verbose_name='Greeting Short')),
                ('invalid_sound', models.CharField(blank=True, default='ivr/ivr-that_was_an_invalid_entry.wav', help_text='Played when and invalid option is chosen', max_length=254, null=True, verbose_name='Invalid Sound')),
                ('exit_sound', models.CharField(blank=True, max_length=254, null=True, verbose_name='Exit Sound')),
                ('confirm_macro', models.CharField(blank=True, help_text='Enter the confirm macro', max_length=254, null=True, verbose_name='Confirm Macro')),
                ('confirm_key', models.CharField(blank=True, help_text='Enter the confirm key', max_length=8, null=True, verbose_name='Confirm Key')),
                ('tts_engine', models.CharField(blank=True, default='flite', help_text='Text to speech engine', max_length=64, null=True, verbose_name='TTS Engine')),
                ('tts_voice', models.CharField(blank=True, default='rms', help_text='Text to speech voice', max_length=254, null=True, verbose_name='TTS Voice')),
                ('confirm_attempts', models.DecimalField(decimal_places=0, default=1, help_text='The maximum number of confirm attempts allowed', max_digits=2, verbose_name='Confirm Attempts')),
                ('timeout', models.DecimalField(decimal_places=0, default=3000, help_text='The number of milliseconds to wait after playing the greeting or the confirm macro', max_digits=5, verbose_name='Timeout')),
                ('exit_app', models.CharField(blank=True, max_length=32, null=True, verbose_name='Exit App.')),
                ('exit_data', models.CharField(blank=True, help_text='Select the exit action to be performed if the IVR exits.', max_length=256, null=True, verbose_name='Exit Action')),
                ('inter_digit_timeout', models.DecimalField(decimal_places=0, default=2000, help_text='The number of milliseconds to wait between digits', max_digits=5, verbose_name='Inter-Digit Timeout')),
                ('max_failiures', models.DecimalField(decimal_places=0, default=1, help_text='Maximum number of retries before exit', max_digits=2, verbose_name='Max Failiures')),
                ('max_timeouts', models.DecimalField(decimal_places=0, default=1, help_text='Maximum number of timeouts before exit', max_digits=2, verbose_name='Max Timeouts')),
                ('digit_len', models.DecimalField(decimal_places=0, default=5, help_text='Maximum number of digits allowed', max_digits=2, verbose_name='Digit Length')),
                ('direct_dial', models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=8, verbose_name='Drect Dial')),
                ('ringback', models.CharField(blank=True, help_text='Defines what the caller will hear while the destination is being called', max_length=128, null=True, verbose_name='Ring Back')),
                ('cid_prefix', models.CharField(blank=True, help_text='Set a prefix on the caller ID name', max_length=32, null=True, verbose_name='CID Name Prefix')),
                ('context', models.CharField(blank=True, db_index=True, help_text='Enter the context', max_length=128, null=True, verbose_name='Context')),
                ('enabled', models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('domain_id', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name_plural': 'IVR Menus',
                'db_table': 'pbx_ivr_menus',
            },
        ),
        migrations.CreateModel(
            name='IvrMenuOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='IVR Menu Option')),
                ('option_digits', models.CharField(blank=True, default='1', max_length=8, null=True, verbose_name='Option')),
                ('option_action', models.CharField(blank=True, default='menu-exec-app', max_length=64, null=True, verbose_name='Option Action')),
                ('option_param', models.CharField(max_length=128, verbose_name='Destination')),
                ('sequence', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Order')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('ivr_menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivrmenus.ivrmenus', verbose_name='IVR Menu')),
            ],
            options={
                'verbose_name_plural': 'IVR Menu Options',
                'db_table': 'pbx_ivr_menu_options',
            },
        ),
    ]
