# Generated by Django 4.0.4 on 2023-11-11 16:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_alter_defaultsetting_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallFlows',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Call Flow')),
                ('name', models.CharField(blank=True, help_text='Enter a name', max_length=64, null=True, verbose_name='Name')),
                ('extension', models.CharField(help_text='Enter the extension number for this call flow', max_length=32, verbose_name='Extension')),
                ('feature_code', models.CharField(default='*30', help_text='Enter the feature code', max_length=8, verbose_name='Feature Code')),
                ('status', models.CharField(choices=[('true', 'Day Mode'), ('false', 'Night Mode')], default='true', help_text='select the status', max_length=8, verbose_name='Status')),
                ('pin_number', models.CharField(blank=True, default='0000', help_text='Enter the pin number', max_length=16, null=True, verbose_name='PIN Number')),
                ('label', models.CharField(blank=True, max_length=32, null=True, verbose_name='Destination label')),
                ('sound', models.CharField(blank=True, help_text='Select the sound to play when the status is set to the destination', max_length=254, null=True, verbose_name='Sound')),
                ('app', models.CharField(blank=True, max_length=32, null=True, verbose_name='Destination App.')),
                ('data', models.CharField(blank=True, help_text='Select the destination', max_length=256, null=True, verbose_name='Destination')),
                ('alternate_label', models.CharField(blank=True, max_length=32, null=True, verbose_name='Alternate label')),
                ('alternate_sound', models.CharField(blank=True, help_text='Select the sound to play when the status is set to the alternate destination', max_length=254, null=True, verbose_name='Alternate Sound')),
                ('alternate_app', models.CharField(blank=True, max_length=32, null=True, verbose_name='Alternate Destination App.')),
                ('alternate_data', models.CharField(blank=True, help_text='Select the alternate destination', max_length=256, null=True, verbose_name='Alternate Destination')),
                ('context', models.CharField(blank=True, db_index=True, help_text='Enter the context', max_length=128, null=True, verbose_name='Context')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='Description')),
                ('dialplan_id', models.UUIDField(blank=True, null=True, verbose_name='Dialplan UUID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('domain_id', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name_plural': 'Call Flows',
                'db_table': 'pbx_call_flows',
            },
        ),
    ]
