# Generated by Django 4.0.4 on 2022-11-09 14:30

from django.db import migrations, models
import django.db.models.deletion
import musiconhold.models
import pbx.commonwidgets
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicOnHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Music On Hold')),
                ('name', models.CharField(default='default', max_length=32, verbose_name='Name')),
                ('path', models.CharField(default='$${sounds_dir}/music/default/', max_length=256, verbose_name='Path')),
                ('rate', models.DecimalField(decimal_places=0, default=8000, max_digits=11, verbose_name='Rate')),
                ('shuffle', models.CharField(default='true', max_length=8, verbose_name='Shuffle')),
                ('channels', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='Channels')),
                ('interval', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='Interval')),
                ('timer_name', models.CharField(default='soft', max_length=32, verbose_name='Timer Name')),
                ('chime_list', models.CharField(blank=True, max_length=64, null=True, verbose_name='Chime List')),
                ('chime_freq', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='Chime Frequency')),
                ('chime_max', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='Chime Max.')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('domain_id', models.ForeignKey(blank=True, db_column='domain_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name_plural': 'Music On Hold',
                'db_table': 'pbx_music_on_hold',
            },
        ),
        migrations.CreateModel(
            name='MohFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Recording')),
                ('filename', pbx.commonwidgets.PbxFileField(upload_to=musiconhold.models.user_directory_path, verbose_name='File Name')),
                ('file_name', models.CharField(max_length=256, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('moh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musiconhold.musiconhold', verbose_name='Hold Music')),
            ],
            options={
                'verbose_name_plural': 'MOH Files',
                'db_table': 'pbx_music_on_hold_files',
                'permissions': (('can_download_file', 'can_download_file'), ('can_upload_file', 'can_upload_file'), ('can_play_file', 'can_play_file')),
            },
        ),
    ]
