# Generated by Django 5.0.1 on 2024-08-10 14:04

import musiconhold.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiconhold', '0002_mohfile_filestore_alter_mohfile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mohfile',
            name='filestore',
            field=models.CharField(default=musiconhold.models.default_filestore, max_length=128, verbose_name='Filestore'),
        ),
    ]
