# Generated by Django 4.0.4 on 2022-11-23 15:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_extensionuser_extension_id'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XmlCdr',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Call Detail Record')),
                ('domain_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Domain Name')),
                ('accountcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='Account Code')),
                ('direction', models.CharField(blank=True, max_length=16, null=True, verbose_name='Direction')),
                ('context', models.CharField(blank=True, max_length=128, null=True, verbose_name='Context')),
                ('caller_id_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Caller ID Name')),
                ('caller_id_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Caller ID Number')),
                ('caller_destination', models.CharField(blank=True, max_length=32, null=True, verbose_name='Destination')),
                ('source_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Source Number')),
                ('destination_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='destination Number')),
                ('start_epoch', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='Start Epoch')),
                ('start_stamp', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('answer_epoch', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='Answer Epoch')),
                ('answer_stamp', models.DateTimeField(blank=True, null=True, verbose_name='Answer Date')),
                ('end_epoch', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='End Epoch')),
                ('end_stamp', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('duration', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='Duration')),
                ('mduration', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='mSec Duration')),
                ('billsec', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='Bill Seconds')),
                ('billmsec', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='Bill mSeconds')),
                ('bridge_uuid', models.UUIDField(blank=True, null=True, verbose_name='Bridge UUID')),
                ('read_codec', models.CharField(blank=True, max_length=16, null=True, verbose_name='Read Codec')),
                ('read_rate', models.CharField(blank=True, max_length=16, null=True, verbose_name='Read Rate')),
                ('write_codec', models.CharField(blank=True, max_length=16, null=True, verbose_name='Write Codec')),
                ('write_rate', models.CharField(blank=True, max_length=16, null=True, verbose_name='Write Rate')),
                ('remote_media_ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='Remote Media IP')),
                ('network_addr', models.CharField(blank=True, max_length=128, null=True, verbose_name='Network Address')),
                ('record_path', models.CharField(blank=True, max_length=256, null=True, verbose_name='Record Path')),
                ('record_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Record Name')),
                ('leg', models.CharField(blank=True, max_length=8, null=True, verbose_name='Leg')),
                ('pdd_ms', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='PDD')),
                ('rtp_audio_in_mos', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='MOS')),
                ('last_app', models.CharField(blank=True, max_length=32, null=True, verbose_name='Last App.')),
                ('last_arg', models.CharField(blank=True, max_length=256, null=True, verbose_name='Last Arg.')),
                ('missed_call', models.BooleanField(blank=True, null=True, verbose_name='Missed Call')),
                ('cc_side', models.CharField(blank=True, max_length=16, null=True, verbose_name='CC Side')),
                ('cc_member_uuid', models.UUIDField(blank=True, null=True, verbose_name='CC Member UUID')),
                ('cc_queue_joined_epoch', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='CC Joined Epoch')),
                ('cc_queue', models.UUIDField(blank=True, null=True, verbose_name='CC Queue UUID')),
                ('cc_member_session_uuid', models.UUIDField(blank=True, null=True, verbose_name='CC Member Session UUID')),
                ('cc_agent_uuid', models.UUIDField(blank=True, null=True, verbose_name='CC Agent UUID')),
                ('cc_agent', models.UUIDField(blank=True, null=True, verbose_name='CC Agent')),
                ('cc_agent_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='CC Agent Type')),
                ('cc_agent_bridged', models.CharField(blank=True, max_length=8, null=True, verbose_name='CC Agent Bridged')),
                ('cc_queue_answered_epoch', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='CC Queue Answered Epoch')),
                ('cc_queue_terminated_epoch', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='CC Queue Terminated Epoch')),
                ('cc_queue_canceled_epoch', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='CC Queue Cancelled Epoch')),
                ('cc_cancel_reason', models.CharField(blank=True, max_length=32, null=True, verbose_name='CC Cancel Reason')),
                ('cc_cause', models.CharField(blank=True, max_length=32, null=True, verbose_name='CC Cause')),
                ('waitsec', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='Wait Seconds')),
                ('conference_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Conference Name')),
                ('conference_uuid', models.UUIDField(blank=True, null=True, verbose_name='Conference UUID')),
                ('conference_member_id', models.CharField(blank=True, max_length=8, null=True, verbose_name='Conference Member ID')),
                ('digits_dialed', models.CharField(blank=True, max_length=64, null=True, verbose_name='Digits Dialled')),
                ('pin_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='PIN Number')),
                ('hangup_cause', models.CharField(blank=True, max_length=32, null=True, verbose_name='Hangup Cause')),
                ('hangup_cause_q850', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Hangup Cause Q.850')),
                ('sip_hangup_disposition', models.CharField(blank=True, max_length=32, null=True, verbose_name='SIP Hangup Disposition')),
                ('xml', models.TextField(blank=True, null=True, verbose_name='XML')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='json')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('domain_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.domain', verbose_name='Domain')),
                ('extension_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.extension', verbose_name='Extension')),
            ],
            options={
                'db_table': 'pbx_xml_cdr',
            },
        ),
    ]
