# Generated by Django 4.0.4 on 2023-11-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlcdr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlcdr',
            name='last_arg',
            field=models.TextField(blank=True, null=True, verbose_name='Last Arg.'),
        ),
    ]
