# Generated by Django 5.0.1 on 2024-05-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlcdr', '0003_alter_xmlcdr_options_calltimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltimeline',
            name='call_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Call UUID'),
        ),
    ]
