# Generated by Django 5.0.1 on 2024-08-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlcdr', '0005_xmlcdr_core_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltimeline',
            name='application_action',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Application Action'),
        ),
        migrations.AddField(
            model_name='calltimeline',
            name='application_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Application Name'),
        ),
    ]
