# Generated by Django 5.0.1 on 2024-08-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlcdr', '0006_calltimeline_application_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltimeline',
            name='general_error',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='General Error'),
        ),
    ]
