# Generated by Django 5.0.1 on 2024-08-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlcdr', '0007_calltimeline_general_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlcdr',
            name='call_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Call UUID'),
        ),
    ]
