# Generated by Django 5.0.1 on 2024-08-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlcdr', '0008_xmlcdr_call_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltimeline',
            name='other_leg_unique_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Other Leg Unique ID'),
        ),
        migrations.AddField(
            model_name='calltimeline',
            name='unique_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Unique ID'),
        ),
    ]
