# Generated by Django 4.0.4 on 2022-05-10 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SipProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='SIP Profile')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('hostname', models.CharField(blank=True, max_length=128, null=True, verbose_name='Hostname')),
                ('enabled', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=8, verbose_name='Enabled')),
                ('description', models.CharField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'pbx_sip_profiles',
            },
        ),
        migrations.CreateModel(
            name='SwitchVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Switch Variable')),
                ('category', models.CharField(choices=[('Tones', 'Tones'), ('Ringtones', 'Ringtones'), ('Music on Hold', 'Music on Hold'), ('SIP', 'SIP'), ('SIP Profile: Internal', 'SIP Profile: Internal'), ('SIP Profile: External', 'SIP Profile: External'), ('Codecs', 'Codecs'), ('XMPP', 'XMPP'), ('Defaults', 'Defaults'), ('Sound', 'Sound'), ('IP Address', 'IP Address'), ('Other', 'Other')], default='Defaults', max_length=64, verbose_name='Category')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('value', models.CharField(blank=True, max_length=254, null=True, verbose_name='Value')),
                ('command', models.CharField(blank=True, choices=[('set', 'set'), ('exec-set', 'exec-set')], default='set', max_length=16, null=True, verbose_name='Command')),
                ('hostname', models.CharField(blank=True, max_length=128, null=True, verbose_name='Hostname')),
                ('enabled', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=8, verbose_name='Enabled')),
                ('sequence', models.DecimalField(decimal_places=0, default=10, max_digits=11, verbose_name='Order')),
                ('description', models.TextField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'pbx_vars',
            },
        ),
        migrations.CreateModel(
            name='SipProfileSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='SIP Profile Setting')),
                ('name', models.CharField(max_length=64, verbose_name='Setting Name')),
                ('value', models.CharField(blank=True, max_length=254, null=True, verbose_name='Value')),
                ('enabled', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=8, verbose_name='Enabled')),
                ('description', models.CharField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('sip_profile_id', models.ForeignKey(db_column='sip_profile_id', on_delete=django.db.models.deletion.CASCADE, to='switch.sipprofile', verbose_name='SIP Profile')),
            ],
            options={
                'db_table': 'pbx_sip_profile_settings',
            },
        ),
        migrations.CreateModel(
            name='SipProfileDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='SIP Profile Domain')),
                ('name', models.CharField(default='all', max_length=128, verbose_name='Name')),
                ('alias', models.CharField(default='false', max_length=8, verbose_name='Alias')),
                ('parse', models.CharField(default='false', max_length=8, verbose_name='Parse')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('sip_profile_id', models.ForeignKey(db_column='sip_profile_id', on_delete=django.db.models.deletion.CASCADE, to='switch.sipprofile', verbose_name='SIP Profile')),
            ],
            options={
                'db_table': 'pbx_sip_profile_domains',
            },
        ),
    ]
