# Generated by Django 4.0.4 on 2022-11-12 13:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Access Control')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('default', models.CharField(choices=[('allow', 'allow'), ('deny', 'deny')], default='deny', max_length=8, verbose_name='Default')),
                ('description', models.CharField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'pbx_access_controls',
            },
        ),
        migrations.CreateModel(
            name='AccessControlNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Access Control None')),
                ('type', models.CharField(choices=[('allow', 'allow'), ('deny', 'deny')], default='deny', max_length=8, verbose_name='Type')),
                ('cidr', models.CharField(blank=True, max_length=64, null=True, verbose_name='CIDR')),
                ('domain', models.CharField(blank=True, max_length=64, null=True, verbose_name='Domain')),
                ('description', models.CharField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('access_control_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switch.accesscontrol', verbose_name='Access Control')),
            ],
            options={
                'db_table': 'pbx_access_control_nodes',
            },
        ),
    ]
