# Generated by Django 4.0.4 on 2023-01-09 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0005_modules_alter_emailtemplate_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('status', models.DecimalField(choices=[(3, 'Permanent'), (1, 'Current'), (0, 'Obsolete')], decimal_places=0, default=1, max_digits=2, max_length=1, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
            ],
            options={
                'verbose_name_plural': 'IP Register',
                'db_table': 'pbx_ip_register',
            },
        ),
        migrations.AlterField(
            model_name='modules',
            name='default_enabled',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Default Enabled'),
        ),
    ]
