# Generated by Django 4.0.4 on 2024-01-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0006_ipregister_alter_modules_default_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipregister',
            name='updated_by',
            field=models.CharField(default='system', max_length=64, verbose_name='Updated by'),
        ),
    ]
