# Generated by Django 4.0.4 on 2024-01-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0007_alter_ipregister_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchvariable',
            name='category',
            field=models.CharField(choices=[('Tones', 'Tones'), ('Ringtones', 'Ringtones'), ('Music on Hold', 'Music on Hold'), ('SIP', 'SIP'), ('SIP Profile: Internal', 'SIP Profile: Internal'), ('SIP Profile: External', 'SIP Profile: External'), ('Codecs', 'Codecs'), ('XMPP', 'XMPP'), ('DSN', 'DSN'), ('Defaults', 'Defaults'), ('Sound', 'Sound'), ('IP Address', 'IP Address'), ('Other', 'Other')], default='Defaults', max_length=64, verbose_name='Category'),
        ),
    ]
