# Generated by Django 4.0.4 on 2022-11-18 19:58

from django.db import migrations, models
import django.db.models.deletion
import pbx.commonwidgets
import uuid
import voicemail.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voicemail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Voicemail')),
                ('vm_id', models.DecimalField(decimal_places=0, max_digits=16, verbose_name='Voicemail ID')),
                ('password', models.CharField(blank=True, max_length=16, null=True, verbose_name='Password')),
                ('greeting_id', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='Greeting ID')),
                ('alternate_greeting_id', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='Alternate Greeting ID')),
                ('mail_to', models.CharField(blank=True, max_length=256, null=True, verbose_name='Mail to')),
                ('sms_to', models.CharField(blank=True, max_length=32, null=True, verbose_name='SMS to')),
                ('cc', models.CharField(blank=True, max_length=64, null=True, verbose_name='CC')),
                ('attach_file', models.CharField(blank=True, choices=[('true', 'True'), ('false', 'False')], default='true', max_length=8, verbose_name='Attach file')),
                ('local_after_email', models.CharField(blank=True, choices=[('true', 'True'), ('false', 'False')], default='true', max_length=8, verbose_name='Keep Local')),
                ('enabled', models.CharField(blank=True, choices=[('true', 'True'), ('false', 'False')], default='true', max_length=8, verbose_name='Enabled')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('domain_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.domain', verbose_name='Domain')),
            ],
            options={
                'db_table': 'pbx_voicemails',
            },
        ),
        migrations.CreateModel(
            name='VoicemailGreeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Recording')),
                ('filename', pbx.commonwidgets.PbxFileField(upload_to=voicemail.models.user_directory_path, verbose_name='File Name')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('voicemail_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voicemail.voicemail', verbose_name='Voicemail')),
            ],
            options={
                'db_table': 'pbx_voicemail_greetings',
                'permissions': (('can_download_greeting', 'can_download_greeting'), ('can_upload_greeting', 'can_upload_greeting'), ('can_play_greeting', 'can_play_greeting')),
            },
        ),
    ]
