# Generated by Django 4.0.4 on 2022-12-11 14:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_extension_call_screen_enabled_and_more'),
        ('voicemail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemail',
            name='alternate_greeting_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Alternate Greeting ID'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='attach_file',
            field=models.CharField(blank=True, choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Attach file'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='enabled',
            field=models.CharField(blank=True, choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='extension_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voicemail', to='accounts.extension', verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='greeting_id',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Greeting ID'),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='local_after_email',
            field=models.CharField(blank=True, choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Keep Local'),
        ),
    ]
