# Generated by Django 4.0.4 on 2022-11-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicemail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemail',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
    ]
