# Generated by Django 5.0.1 on 2024-08-10 14:04

import voicemail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicemail', '0003_voicemailgreeting_filestore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemailgreeting',
            name='filestore',
            field=models.CharField(default=voicemail.models.default_filestore, max_length=128, verbose_name='Filestore'),
        ),
    ]
