# Generated by Django 5.0.1 on 2024-08-21 11:46

import django.db.models.deletion
import pbx.commonwidgets
import uuid
import voicemail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicemail', '0004_alter_voicemailgreeting_filestore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemail',
            name='attach_file',
            field=models.CharField(blank=True, choices=[('false', 'None'), ('true', 'Audio file attachment'), ('link', 'Download link')], default='true', max_length=8, verbose_name='Attach file'),
        ),
        migrations.CreateModel(
            name='VoicemailDestinations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Recording')),
                ('voicemail_dest', models.UUIDField(blank=True, null=True, verbose_name='Destination')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('voicemail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicemail.voicemail', verbose_name='Voicemail')),
            ],
            options={
                'verbose_name_plural': 'Voicemail Destinations',
                'db_table': 'pbx_voicemail_destinations',
            },
        ),
        migrations.CreateModel(
            name='VoicemailMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Message')),
                ('filename', pbx.commonwidgets.PbxFileField(storage=voicemail.models.select_storage, upload_to=voicemail.models.user_directory_path, verbose_name='File Name')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('filestore', models.CharField(default=voicemail.models.default_filestore, max_length=128, verbose_name='Filestore')),
                ('caller_id_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Caller ID Name')),
                ('caller_id_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Caller ID Number')),
                ('duration', models.DecimalField(decimal_places=0, default=0, max_digits=32, verbose_name='Duration')),
                ('status', models.CharField(blank=True, max_length=64, null=True, verbose_name='Status')),
                ('read', models.DateTimeField(blank=True, null=True, verbose_name='Read Date')),
                ('transcription', models.TextField(blank=True, null=True, verbose_name='Transcription')),
                ('base64', models.TextField(blank=True, null=True, verbose_name='Base64')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('voicemail_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voicemail.voicemail', verbose_name='Voicemail')),
            ],
            options={
                'db_table': 'pbx_voicemail_messages',
                'permissions': (('can_download_message', 'can_download_message'), ('can_upload_message', 'can_upload_message'), ('can_play_message', 'can_play_message')),
            },
        ),
        migrations.CreateModel(
            name='VoicemailOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Voicemail Option')),
                ('option_digits', models.CharField(blank=True, default='1', max_length=8, null=True, verbose_name='Option')),
                ('option_action', models.CharField(blank=True, default='menu-exec-app', max_length=64, null=True, verbose_name='Option Action')),
                ('option_param', models.CharField(max_length=128, verbose_name='Destination')),
                ('sequence', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Order')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('voicemail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicemail.voicemail', verbose_name='Voicemail')),
            ],
            options={
                'verbose_name_plural': 'Voicemail Options',
                'db_table': 'pbx_voicemail_options',
            },
        ),
    ]
