# Generated by Django 5.0.1 on 2024-08-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicemail', '0005_alter_voicemail_attach_file_voicemaildestinations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemailmessages',
            name='status',
            field=models.CharField(default='new', max_length=64, verbose_name='Status'),
        ),
    ]
