# Generated by Django 4.0.4 on 2022-11-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialplans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialplan',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=32, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='dialplandetail',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Type'),
        ),
    ]
