# Generated by Django 4.0.4 on 2022-11-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialplans', '0002_alter_dialplan_category_alter_dialplandetail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialplandetail',
            name='data',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Data'),
        ),
    ]
