# Generated by Django 4.0.4 on 2022-11-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialplans', '0003_alter_dialplandetail_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialplandetail',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Type'),
        ),
    ]
