# Generated by Django 4.0.4 on 2022-11-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialplans', '0004_alter_dialplandetail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialplan',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='General', max_length=32, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='dialplan',
            name='context',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='dialplan',
            name='destination',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], db_index=True, default='true', max_length=8, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='dialplan',
            name='hostname',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Hostname'),
        ),
    ]
