# Generated by Django 4.0.4 on 2023-11-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialplans', '0005_alter_dialplan_category_alter_dialplan_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialplan',
            name='destination',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], db_index=True, default='false', max_length=8, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='dialplan',
            name='dp_continue',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=8, verbose_name='Continue'),
        ),
        migrations.AlterField(
            model_name='dialplan',
            name='enabled',
            field=models.CharField(blank=True, choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled'),
        ),
    ]
