# Generated by Django 5.0.1 on 2024-02-03 19:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialplans', '0006_alter_dialplan_destination_and_more'),
        ('tenants', '0004_alter_defaultsetting_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialplanExcludes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Dialplan Excludes')),
                ('domain_name', models.CharField(db_index=True, max_length=128, verbose_name='Domain Name')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Dialplan Name')),
                ('app_id', models.UUIDField(verbose_name='AppUuid')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('synchronised', models.DateTimeField(blank=True, null=True, verbose_name='Synchronised')),
                ('updated_by', models.CharField(max_length=64, verbose_name='Updated by')),
                ('domain_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.domain', verbose_name='Domain')),
            ],
            options={
                'db_table': 'pbx_dialplan_excludes',
            },
        ),
    ]
