# Generated by Django 5.0.1 on 2024-02-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialplans', '0007_dialplanexcludes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialplanexcludes',
            options={'verbose_name_plural': 'Dialplan Excludes'},
        ),
    ]
