# Generated by Django 5.0.1 on 2024-03-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialplans', '0008_alter_dialplanexcludes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialplan',
            name='number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Number'),
        ),
    ]
