# Generated by Django 5.0.1 on 2024-04-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialplans', '0009_alter_dialplan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialplandetail',
            name='enabled',
            field=models.CharField(blank=True, choices=[('false', 'False'), ('true', 'True')], default='true', max_length=8, verbose_name='Enabled'),
        ),
    ]
